Added borgbackup to domc

diff --git a/domc b/domc
--- a/domc
+++ b/domc
@@ -13,8 +13,8 @@ trap '' SIGINT SIGQUIT SIGTSTP
 ########################
 
 # Set debug
-DEBUG=1
-set -x
+DEBUG=0
+#set -x
 
 # Define command locations
 DO_BIN=/usr/bin/doctl
@@ -28,7 +28,7 @@ PURPLE="\033[0;35m"       # Purple
 
 # Configure Global variables
 ENV_CONF=${1:-env.conf}
-WAN_IP=$(dig @resolver1.opendns.com ANY myip.opendns.com +short)
+WAN_IP=$(dig -4 @resolver1.opendns.com ANY myip.opendns.com +short)
 
 
 ########################
@@ -133,7 +133,7 @@ power_state:
 EOF
 }
 
-function droplet_create {
+function droplet_create() {
 local   parms=(compute droplet create $DROPLET_HOSTNAME --wait --size $DROPLET_SIZE --image $DROPLET_IMAGE --region $DROPLET_REGION --ssh-keys $DROPLET_SSHKEY --tag-names $DROPLET_TAG)
 local	domain=${DROPLET_HOSTNAME#*.}
 local   host=${DROPLET_HOSTNAME%%.*}
@@ -175,7 +175,7 @@ done
 
 }
 
-function droplet_delete {
+function droplet_delete() {
 local droplet_id=""
 
 # Find and delete all Droplets with our tag
@@ -241,12 +241,24 @@ log "Attaching Firewall"
 firewall_attach && { log "Firewall installed successfully."; } || { log "Error installing Firewall!"; return 0; }; 
 
 log "Configuring SSH"
-droplet_sshBatch "$SCRIPT_CONFIG" "DROPLET_SSH_PORT=$DROPLET_SSH_PORT DROPLET_SSH_USER=$DROPLET_SSH_USER" "SSH_config"  && { log "SSH configured successfully."; } || { log "Error configuring SSH!"; return 0; }          
-
+droplet_sshBatch "$SCRIPT_CONFIG" "DROPLET_SSH_PORT=$DROPLET_SSH_PORT DROPLET_SSH_USER=$DROPLET_SSH_USER" "SSH_config"  && { log "SSH configured successfully."; } || { log "Error configuring SSH!"; return 0; }
+ssh-keygen -R "[$(dig -4 @resolver1.opendns.com ANY $DROPLET_HOSTNAME +short)]:$DROPLET_SSH_PORT"
 }
 
 
-function volume_attach {
+function droplet_backup() {
+#set -x
+
+backup_repokey="$(cat $BACKUP_REPOKEY)"
+backup_sshid="$(cat $BACKUP_SSHID)"
+
+log "Configuring Borgbackup"
+droplet_sshBatch "$SCRIPT_CONFIG" "MAILCOW_VOLUME=$MAILCOW_VOLUME MAILCOW_BACKUP_DIR=$MAILCOW_BACKUP_DIR BACKUP_REPO=$BACKUP_REPO BACKUP_REPOKEY=\"$backup_repokey\" BACKUP_HOSTID=\"$BACKUP_HOSTID\" BACKUP_SSHID=\"$backup_sshid\"" "Borg_install"  && { log "Borgbackup configured successfully."; } || { log "Error configuring Borgbackup!"; return 0; }
+
+
+}
+
+function volume_attach() {
 local droplet_id=""
 local volume_id=""
 
@@ -266,9 +278,11 @@ volume_id=$($DO_BIN compute volume list | grep "$MAILCOW_VOLUME" | awk '{ print 
 
 # Attach volume	
 if [ ! -z $droplet_id ] && [ ! -z $volume_id ]; then
-	log "Attaching Volume: $volume_id to Droplet: $droplet_id"
-	$DO_BIN compute volume-action attach $volume_id $droplet_id && log "Volume successfully attached" || { log "Problem attaching volume!"; return 1; }
 	
+	if [ "$($DO_BIN compute droplet list | grep "$DROPLET_TAG" | awk '{ print $14 }')" != "$volume_id" ]; then
+		log "Attaching Volume: $volume_id to Droplet: $droplet_id"
+		$DO_BIN compute volume-action attach $volume_id $droplet_id && log "Volume successfully attached" || { log "Problem attaching volume!"; return 1; }
+	fi	
 	# Workaround DO Bug in automount on Debian 9.6
 	droplet_sshBatch "$SCRIPT_CONFIG" "MAILCOW_VOLUME=$MAILCOW_VOLUME" "Volume_mount" && log "Volume successfully mounted" ||  { log "Problem creating mount!"; return 1; };
 else
@@ -279,7 +293,7 @@ fi
 }
 
 
-function volume_detach {
+function volume_detach() {
 local droplet_id=""
 local volume_id=""
 
@@ -334,8 +348,8 @@ local args=(compute ssh $DROPLET_HOSTNAME --ssh-port $DROPLET_SSH_PORT --ssh-use
 trap - SIGINT
 [[ ! -f ${1:-} ]] && log "Error: SSH batch file doesn't exist"
 [[ $# -eq 1 ]] && { $DO_BIN "${args[@]}" < $1 || { log "Error in SSH: $?"; trap ' ' SIGINT; return 0; } }
-[[ $# -eq 2 && ! -z ${2:-} ]] && { $DO_BIN "${args[@]}" < <(echo ${2:-}; cat $1) || { log "Error in SSH: $?"; trap ' ' SIGINT; return 0; } }
-[[ $# -eq 3 && ! -z ${3:-} ]] && { $DO_BIN "${args[@]}" < <(echo ${2:-}; cat $1; echo $3) || { log "Error in SSH: $?"; trap ' ' SIGINT; return 0; } }
+[[ $# -eq 2 && ! -z ${2:-} ]] && { $DO_BIN "${args[@]}" < <(echo "${2:-}"; cat $1) || { log "Error in SSH: $?"; trap ' ' SIGINT; return 0; } }
+[[ $# -eq 3 && ! -z ${3:-} ]] && { $DO_BIN "${args[@]}" < <(echo "${2:-}"; cat $1; echo $3) || { log "Error in SSH: $?"; trap ' ' SIGINT; return 0; } }
 trap ' ' SIGINT; 
 
 }
@@ -394,7 +408,8 @@ droplet_ssh "cd /opt/mailcow-dockerized/ && sudo docker-compose logs -f --tail=1
 
 function mailcow_backup() {
 log "Backing up mailcow config"
-droplet_ssh "sudo MAILCOW_BACKUP_LOCATION=$MAILCOW_BACKUP_DIR /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all"
+#droplet_ssh "sudo MAILCOW_BACKUP_LOCATION=$MAILCOW_BACKUP_DIR /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all"
+droplet_ssh "sudo MAILCOW_BACKUP_LOCATION=$MAILCOW_BACKUP_DIR /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup crypt redis rspamd postfix mysql"
 }
 
 function docker_prune() {
@@ -525,12 +540,14 @@ while [ "$choice" != x ]; do
         echo "1.  Create Droplet 		- Create and configure mailcow Droplet"
         echo "2.  Configure Droplet		- Configure and Secure Droplet"
         echo "3.  Install Mailcow 		- Create and configure mailcow Droplet"
+        echo "4.  Configure Backup 		- Configure mailcow backup"
         echo "x.  Exit"
         read -p "Enter choice [ 0 - 5 ] " choice
         case $choice in
 		1) droplet_create; pause ;;
                 2) droplet_configure; pause ;;
                 3) mailcow_install; pause ;;
+                4) droplet_backup; pause ;;
                 5) pause ;;
                 x) return 0;;
                 *) echo -e "${RED}Error...${STD}" && sleep 1
diff --git a/script_Config b/script_Config
--- a/script_Config
+++ b/script_Config
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -euo pipefail
-set -x
+#set -x
 
 ########################
 ### SCRIPT VARIABLES ###
@@ -55,11 +55,10 @@ Type=ext4
 WantedBy = multi-user.target" | tee /etc/systemd/system/$mnt_dir.mount
 systemctl daemon-reload
 systemctl enable $mnt_dir.mount
-else
-	echo "Mount script exists"
-fi
-
 systemctl start $mnt_dir.mount
+else
+	echo "Backup volume mount script exists"
+fi
 
 }
 
@@ -110,9 +109,8 @@ Type=ext4
 WantedBy = multi-user.target" | tee /etc/systemd/system/mnt-$mnt_dir.mount
 systemctl daemon-reload
 systemctl enable mnt-$mnt_dir.mount
-fi
-
 systemctl start mnt-$mnt_dir.mount
+fi
 
 }
 
@@ -169,6 +167,97 @@ UsePrivilegeSeparation sandbox
 AllowUsers $DROPLET_SSH_USER" | tee /etc/ssh/sshd_config
 systemctl restart sshd
 }
+
+
+function Borg_install() {
+## systemd, pre_hook for mailcow backup
+
+# Load variable
+local mnt_dir=$(echo "$MAILCOW_VOLUME" | sed -e 's/-/_/g')
+source /mnt/$mnt_dir/mailcow.conf
+CMPS_PRJ=$(echo $COMPOSE_PROJECT_NAME | tr -cd "[A-Za-z-_]")
+
+
+# install borgmatic
+docker pull monachus/borgmatic
+
+# install systemd
+
+# add config directory
+[[ ! -d "/etc/borgmatic" ]] && mkdir -p /etc/borgmatic
+[[ ! -d "~/.ssh" ]] && mkdir -p ~/.ssh
+
+
+# install borgmatic conf
+[[ ! -f "/etc/borgmatic/config.yaml" ]] && echo "Copying borgmatic config" || echo "Overwriting borgmatic config"
+echo -e "location:
+    source_directories:
+        - /vmail
+        - /mailcow
+
+    one_file_system: true
+    repositories:
+        - $BACKUP_REPO
+
+    exclude_patterns:
+        - 'dovecot-uidlist.lock'
+        - ~/*/.cache
+
+    exclude_caches: true
+    exclude_if_present: .nobackup
+
+storage:
+    #compression: auto,zstd
+    archive_name_format: '{hostname}-{now}'
+
+retention:
+    keep_daily: 3
+    keep_weekly: 4
+    keep_monthly: 12
+    keep_yearly: 2
+    prefix: '{hostname}-'
+
+consistency:
+    checks:
+        # uncomment to always do integrity checks. (takes long time for large repos)
+        - repository
+        #- disabled
+
+    check_last: 3
+    prefix: '{hostname}-'
+" | tee /etc/borgmatic/config.yaml
+
+# install repo key
+[[ ! -f "/etc/borgmatic/repokey" ]] && echo "Copying repo key" || echo "Overwriting repo key"
+echo -e "$BACKUP_REPOKEY" | tee /etc/borgmatic/repokey
+chmod 600 /etc/borgmatic/repokey
+
+#install ssh key
+[[ ! -f "~/.ssh/id_borg" ]] && echo "Copying ssh id" || echo "Overwriting ssh id"
+echo -e "$BACKUP_SSHID" | tee ~/.ssh/id_borg
+chmod 600 ~/.ssh/id_borg
+
+# install borg backup host keys and test
+local hostname="$(echo $BACKUP_HOSTID | awk '{ print $1 }')"
+local pubkey="$(echo $BACKUP_HOSTID | awk '{ print $3 }')"
+if [[ ! -f "~/.ssh/known_hosts" ]]; then
+ssh-keyscan -H $hostname | tee ~/.ssh/known_hosts
+else
+ssh-keyscan -H $hostname | tee -a ~/.ssh/known_hosts
+fi
+[[ $(ssh-keygen -F "$hostname" |grep "$pubkey") ]] && echo "Backup host authenticated" || { echo "Backup host authentication error"; exit 1; }
+
+
+# execute a backup
+docker run --rm -e BORG_PASSCOMMAND='cat /borgmatic/repokey' -e BORG_RSH='ssh -i /root/.ssh/id_borg' -v $(docker volume ls -qf name=${CMPS_PRJ}_vmail-vol-1):/vmail:ro -v $MAILCOW_BACKUP_DIR:/mailcow -v ~/.ssh:/root/.ssh -v /etc/borgmatic:/borgmatic:ro monachus/borgmatic --verbosity 1 -c /borgmatic/config.yaml
+
+# execute a test restore
+local archive="$(docker run --rm -e 'BORG_PASSCOMMAND=cat /borgmatic/repokey' -e 'BORG_RSH=ssh -i ~/.ssh/id_borg' -v ~/.ssh:/root/.ssh -v /etc/borgmatic:/borgmatic:ro monachus/borgmatic -c /borgmatic/config.yaml --list |tail -n 1 |awk '{ print $1 }')"
+docker run --rm -e 'BORG_PASSCOMMAND=cat /borgmatic/repokey' -e 'BORG_RSH=ssh -i ~/.ssh/id_borg' -v ~/.ssh:/root/.ssh -v /etc/borgmatic:/borgmatic:ro monachus/borgmatic borg extract --dry-run --list $BACKUP_REPO::$archive
+
+exit 0
+}
+
 
 
 ####################
